server:
  port: 8080

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

spring:
  cloud:
    gateway:
      routes:
        - id: pr-esp
          uri: lb://pr-esp/esp
          predicates:
            - Path=/esp/**
        - id: pr-base
          uri: lb://pr-base/energy
          predicates:
            - Path=/energy/**
        - id: pr-base
          uri: lb://pr-base/storaged
          predicates:
            - Path=/storaged/**
  application:
    name: pr-gateway
